all:
  children:
    dev:
      hosts:
        todo-dev:
          ansible_host: "15.188.210.106"
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ../todo-app/todo-app.pem
          app_env: dev
    prod:
      hosts:
        todo-prod:
          ansible_host: "13.39.134.65"
          ansible_user: ubuntu
          ansible_ssh_private_key_file: ../todo-app/todo-app.pem
          app_env: prod